# consider helm install to be failed after 10 minutes
helm-extra-args: --timeout 300s
check-version-increment: false
debug: true
chart-dirs:
  - ./scalardl
  - ./schema-loading
validate-maintainers: false
namespace: default
release-label: test
