{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) ( .Values.ledger.prometheusRule.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus-operator
    release: prometheus
  name: {{ include "scalardl.fullname" . }}-ledger-prometheus-alerts-rules
{{- if .Values.ledger.prometheusRule.namespace }}
  namespace: {{ .Values.ledger.prometheusRule.namespace }}
{{- end }}
spec:
  groups:
  - name: LedgerAlerts
    rules:
    - alert: LedgerClusterDown
      expr: kube_deployment_spec_replicas{deployment="{{ include "scalardl.fullname" . }}-ledger"} - kube_deployment_status_replicas_unavailable{deployment="{{ include "scalardl.fullname" . }}-ledger"} == 0
      for: 1m
      labels:
        severity: critical
        app: Ledger
      annotations:
        summary: 'Ledger cluster is down'
        description: 'Ledger cluster is down, no resquest can be process'

    - alert: LedgerClusterDegraded
      expr: kube_deployment_status_replicas_unavailable{namespace="{{ .Release.Namespace }}", deployment="{{ include "scalardl.fullname" . }}-ledger"} >= 1
      for: 1m
      labels:
        severity: warning
        app: Ledger
      annotations:
        summary: 'Ledger cluster is running in a degraded mode'
        description: 'Ledger cluster is running in a degraded mode, some of the Ledger pods are not healthy'

    - alert: LedgerPodsPending
      expr: kube_pod_status_phase{namespace="{{ .Release.Namespace }}", pod=~"^{{ include "scalardl.fullname" . }}-ledger-.*", phase="Pending"} > 0
      for: 1m
      labels:
        severity: warning
        app: Ledger
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has been in pending status for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} in pending status.'
    
    - alert: LedgerPodsError
      expr: kube_pod_container_status_waiting_reason{namespace="{{ .Release.Namespace }}",reason!="ContainerCreating",pod=~"^{{ include "scalardl.fullname" . }}-ledger-.*"} > 0
      for: 1m
      labels:
        severity: warning
        app: Ledger
      annotations:
        description: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error for more than 1 minute.'
        summary: 'Pod {{`{{$labels.pod}}`}} in namespace {{`{{$labels.namespace}}`}} has an error status.'
{{- end }}
